include("${CMAKE_SOURCE_DIR}/.cget/core.cmake" REQUIRED)

CGET_HAS_DEPENDENCY(openvr REGISTRY VERSION master)
CGET_HAS_DEPENDENCY(glew REGISTRY VERSION master)
CGET_HAS_DEPENDENCY(SDL2 REGISTRY VERSION master)
CGET_HAS_DEPENDENCY(assimp GITHUB assimp/assimp VERSION v3.3.1)
