include("${CMAKE_SOURCE_DIR}/.cget/core.cmake" REQUIRED)

CGET_HAS_DEPENDENCY(OpenVR REGISTRY VERSION master)
CGET_HAS_DEPENDENCY(glew REGISTRY VERSION master)
CGET_HAS_DEPENDENCY(SDL2 REGISTRY VERSION master)
CGET_HAS_DEPENDENCY(assimp GITHUB assimp/assimp VERSION v3.3.1)
CGET_HAS_DEPENDENCY(OpenSSL REGISTRY VERSION master)
CGET_HAS_DEPENDENCY(Poco GITHUB pocoproject/poco VERSION poco-1.7.7-release
  COMPONENTS Util Foundation 
)
CGET_HAS_DEPENDENCY(Freetype REGISTRY VERSION master)
CGET_HAS_DEPENDENCY(MYGUI GITHUB MyGUI/mygui VERSION MyGUI3.2.2)

CGET_HAS_DEPENDENCY(OpenCV GITHUB opencv/opencv VERSION 3.1.0
  OPTIONS
  -DBUILD_WITH_STATIC_CRT:BOOL=OFF
  -DBUILD_opencv_java:BOOL=OFF
  -DBUILD_opencv_calib3d:BOOL=ON
  -DBUILD_opencv_features2d:BOOL=OFF
  -DBUILD_opencv_flann:BOOL=OFF
  -DBUILD_opencv_ml:BOOL=OFF
  -DBUILD_opencv_videoio:BOOL=OFF
  -DBUILD_opencv_video:BOOL=OFF
  -DBUILD_opencv_superres:BOOL=OFF
  -DBUILD_opencv_highgui:BOOL=OFF
  -DBUILD_opencv_python:BOOL=OFF
  -DBUILD_opencv_python2:BOOL=OFF
  -DBUILD_opencv_python3:BOOL=OFF
  -DBUILD_opencv_photo:BOOL=OFF
  -DBUILD_opencv_shape:BOOL=OFF
  -DBUILD_FAT_JAVA_LIB:BOOL=OFF
  -DBUILD_TESTS:BOOL=OFF
  -DBUILD_PERF_TESTS:BOOL=OFF
  -DBUILD_PACKAGE:BOOL=OFF
  -DBUILD_DOCS:BOOL=OFF
  -DBUILD_opencv_apps:BOOL=OFF
  -DANDROID:BOOL=OFF
  -DWITH_VTK:BOOL=OFF
  -DWITH_WIN32UI:BOOL=OFF)
  
